### ISSUE TITLE
BCrypt Decrypt (2) failed with status: -1073700862

### ISSUE THREAD

**Issue by Fomovet** [shaddy43/BrowserSnatch#2]
OS Version: Windows 11
OS Architecture: 64-bit
Browser Name: Chrome
Browser Version: 129.0.6668.59

Log Output

```
C:\Users\0xTest\Desktop\hack-browser-data-windows-64bit>BrowserSnatch64.exe -cookies
Target Chromium Browser cookies...
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
BCrypt Decrypt (2) failed with status: -1073700862
Stealer db path: C:\Users\0xTest\AppData\Local\Temp\upX1i0

**Comment by shaddy43** [comment]
Please check if the password versions stored in your chrome browsers are older than v10. Anything older than v10 passwords will not be decrypted. BrowserSnatch works on latest v10,v11 version encrypted passwords only.

**Comment by Fomovet** [comment]
> 请检查您 chrome 浏览器中存储的密码版本是否早于 v10。任何早于 v10 的密码都不会被解密。BrowserSnatch 仅适用于最新的 v10、v11 版本加密密码。cookie 也是如此！
> 
> 您可以在 sqlite db 浏览器中检查密码或 cookies 文件的加密数据版本。每个加密数据都附加了版本元信息，如下面的屏幕截图所示：
> 
> <img alt="截图于 2024-09-19 下午 5 07 22" width="876" src="https://private-user-images.githubusercontent.com/34940939/369031515-291f28ef-985a-49b9-87b4-13c0db944475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTcyODIsIm5iZiI6MTcyNjc1Njk4MiwicGF0aCI6Ii8zNDk0MDkzOS8zNjkwMzE1MTUtMjkxZjI4ZWYtOTg1YS00OWI5LTg3YjQtMTNjMGRiOTQ0NDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE0NDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YjJiY2ViZjFiODUxYmM1ZTkzOGQwMTVmNWVhMmI2Y2ZmYTZlZWU1OTFiMDhlY2I4M2RiZDIwMTdhNmE4ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7EPunWV6O0AnXx1qK4hoZIf6AeGJzwdt3LCJ-be8iH0">







The latest version of Chrome cookie encryption is v20
![image](https://github.com/user-attachments/assets/f497fd92-22a8-4cb3-98a3-1d4b71464cd6)

**Comment by Fomovet** [comment]
> Please check if the password versions stored in your chrome browsers are older than v10. Anything older than v10 passwords will not be decrypted. BrowserSnatch works on latest v10,v11 version encrypted passwords only. Same goes for the cookies !
> 
> You can check the version of you encrypted data in sqlite db browser for passwords or cookies file. Every encrypted data has prepended version meta info as shown in the screenshot below:
> 
> <img alt="Screenshot 2024-09-19 at 5 07 22 PM" width="876" src="https://private-user-images.githubusercontent.com/34940939/369031515-291f28ef-985a-49b9-87b4-13c0db944475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTc3ODAsIm5iZiI6MTcyNjc1NzQ4MCwicGF0aCI6Ii8zNDk0MDkzOS8zNjkwMzE1MTUtMjkxZjI4ZWYtOTg1YS00OWI5LTg3YjQtMTNjMGRiOTQ0NDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE0NTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZDFjOTVhNmM1OGJmM2NkNjFmMmRmNTc0YjYxMjg4OTE5ZmI4YmZkNDY0YWRlYjQ4MjZmOWRhMWU2YzY0YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JSKqV9lrsN279HlJjHURIT4rv7VEGhvnu7eo5ng-QaA">

**The latest version of Chrome cookie encryption is v20**
![image](https://github.com/user-attachments/assets/4c193005-f4bc-4273-8be0-0d82ba717b6e)

**Comment by shaddy43** [comment]
Google has recently updated its security policy on saving encrypted cookies. Unlike before, they encryption keys are not only secured by DPAPI (which could be easily accessed by malware running with the same user mode privileges) but now chrome has introduced something called **Application-Bound** Encryption Primitives which basically improves on DPAPI by running a SYSTEM Level Chrome Service which first authenticates if the application requesting the key is Chrome itself and then uses SYSTEM level privileges to decrypt keys with DPAPI and return to the requesting process (which would be chrome).

<img width="703" alt="Screenshot 2024-09-19 at 10 26 08 PM" src="https://github.com/user-attachments/assets/2ee5eb17-2dd4-4944-b883-84fc54959872">

Because the App-Bound service is running with system privileges, attackers need to do more than just coax a user into running a malicious app. Now, the malware has to gain system privileges, or inject code into Chrome. This complicates the process of stealing chrome cookies.
For now, chrome passwords saving policy has not been shifted to this mechanism but eventually it will. So I need to do some R&D on how to include this bypass in upcoming versions of BrowserSnatch.

For your reference:
https://security.googleblog.com/2024/07/improving-security-of-chrome-cookies-on.html

**Comment by shaddy43** [comment]
Will be handled in upcoming versions

**Comment by shaddy43** [comment]
Chrome 1.27 and greater version cookie decryption is now available in latest release. There is a separate command line parameter for snatching latest app bound encrypted chrome cookies.

use: ./BrowserSnatch.exe -cookies -chrome_app_bound

**Comment by hubert3** [comment]
Microsoft Edge for Business v132.0.2957.127 (Official build) (64-bit), trying to dump cookies

![Image](https://github.com/user-attachments/assets/2de02cc2-8eaa-4587-811c-bf7a6cabd19d)

BrowserSnatch runs without errors but Edge quits and the generated sqlite db contains no data :(

Running with -cookies -chrome_app_bound is only relevant for Google Chrome I assume, but that fails with 'Failed to start process. Error: 3'
